### PR TITLE
New version bump

### PR DESCRIPTION
**Pull request by alx3dev**
So this is what I did so far, important methods are documented, others will be. `README.md` should be updated with new info, but I will add more methods, so it's better to wait for better doc to update readme. Since this introduce breaking changes, version should go on `2.0.0`. I didn't put my name anywhere in code, it's your name everywhere. Version `2.1.0` will introduce easier method working (for message creation, keyboard, rich media...). I did not fully tested it yet, but rspec passed. Rubocop complain about some missing documentation, and two methods that are too big. It also complain about `get_` and `set_` for `get_online` and `set_webhook`, but that should stay like that and follow viber API.

### CODE REVIEW

**Comment by ademdc** [comment]
@alx3dev It looks excellent! I went through it and even though I would do some small stuff a bit different, I still like the implementation overall. +1

**Comment by ademdc** [comment]
@alx3dev just one question, why is the required ruby version in the .gemspec file '>= 3.0.1'? Is it necessary?

**Comment by alx3dev** [comment]
Change that version, I did it automatically with script. I plan to add more stuff here, if you have any idea, feel free to share. Constants should use ENV variables as default configuration, so that's first what I would like to implement here. After that, construction of messages, pictures, rich media... Working on some crypto-trade bot at the moment, so i plan to connect it with this gem when I am done.

Edit: Ruby 3.0 is way faster then ruby 2, and introduce new stuff, in Ruby 3.1 even more. That's why I always put more then 3 for version requirement for new gems. But this is not my new gem :) I think it's not necessary for this, everything should work with `>= 2.6`

**Comment by ademdc** [comment]
@alx3dev You are right about the speed of Ruby 3.0. But maybe it is better to have the requirement for `>=2.6`, so it can be used by more projects which don't yet have ruby 3. I will change that. 

The crypto bot sounds interesting :)

**Pull request merged**
